title: Hengineered
description: Custom prosthetic legs for our feathered friends
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Contact: https://docs.google.com/forms/d/e/1FAIpQLScz2m5qK1U-eMnMx-DZb3vAoLCWhzdGKjJZuZZyoxB5vLwKPw/viewform?usp=publish-editor

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/chicken.png"

color_scheme: dark

search_enabled: false

nav_enabled: true

ga_tracking: G-J9FT0SYBDB
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)